### ISSUE TITLE
Fast5 File Accessibility

### ISSUE THREAD

**Issue by ssomalra** [adnaniazi/tailfinder#69]
Hello,

I'm attempting to execute Tailfindr on the RNA Replicate 2 (SQK-RNA001 +RT) sample from the Tailfindr paper. After performing basecalling using Guppy, I obtained the modified Fast5 files containing the Event/Move table under 'Basecall_1D_001'.

However, during the execution of Tailfindr, one of the Fast5 files encounters a file accessibility error, as illustrated below. I've also applied chmod 777 to ensure file access, yet the problem persists.

Any help regarding the error would be much appreciated. Thank you.

<img width="649" alt="Screen Shot 2024-03-26 at 10 54 28 PM" src="https://github.com/adnaniazi/tailfindr/assets/116883221/5d96a6a5-0460-4ecc-b53e-c9e46df41e19">

**Comment by adnaniazi** [comment]
Hi,

You probably have this file in question open in hdfview or some other program while tailfindr is trying to read it. Fast5 files cannot be read by two programs at the same time. Please close the file elsewhere and then run tailfindr again.

Adnan

**Comment by ssomalra** [comment]
Thank you for the quick response! I just closed down another program and reran tailfindr. I'm still getting the same error unfortunately.

**Comment by adnaniazi** [comment]
I still think some other program is using the fast5 files. I know this error very well. Copy the data to some other location, and then run tailfindr on fast5 files in that new location. Try running on a small subset of fast5 files first instead of the full dataset.

**Comment by ssomalra** [comment]
Hello,

I copied the data to a different location and ran on a small subset of fast5 files and am still getting the same error (but for a different file). Apart from Google Chrome and Rstudio on a remote desktop (where I'm running tailfindr), no other programs/applications are running.

**Comment by adnaniazi** [comment]
Can you send me one of your FAST5 files. I will have a look

**Comment by ssomalra** [comment]
Just sent! Thank you.

**Comment by adnaniazi** [comment]
Hi,

I have tried to run tailfindr on the file you sent me. Worked fine.

I think there is some problem at the compute resource that you are running tailfindr on.

Try installing tailfindr on a Unix system of your own, and run it on a small subset to test if you manage to make it work.

I can confirm from my side that the read you sent me is fine, and tailfindr works on it. The problem with file permission always happens when one of the fast5 that tailfindr wants to access is already being accessed by some other program and is therefore being blocked for tailfindr, which results in tailfindr crashing.

Adnan

**Comment by ssomalra** [comment]
Hi Adnan,

I was able to get Tailfindr to run on the files. Just restarted rstudio and reloaded libraries and it worked fine this time around. 

Thanks for the help
-Sahiti

**Comment by adnaniazi** [comment]
Glad to hear that it worked.

Best wishes,
Adnan
