### ISSUE TITLE
Tails look shorter than what they should be, discrepencies tailfindR/dorado,

### ISSUE THREAD

**Issue by ArnaudStigliani** [adnaniazi/tailfinder#71]
Dear developers,
Recently, I have been comparing tailfindR 1.3 (jamie-Seq branch) and Dorado outputs.
When doing so, I noticed that pA tails (but not pT tails) are in some cases way longer according to Dorado (see blue dots on the plot).
![image](https://github.com/adnaniazi/tailfindr/assets/26601637/759ddd99-8d72-47e0-809c-4aee74f85280)

I have had a look at some of these reads, below are two examples (output by tailfindR) with the predicted pA in red:
![image](https://github.com/adnaniazi/tailfindr/assets/26601637/db0aaf22-0eef-4c89-9d38-843f0829f9e9)
![image](https://github.com/adnaniazi/tailfindr/assets/26601637/e473d0ef-afaa-4340-b261-dca8c258baff)

It seems that the pA fraction of these specific reads should be longer than tailfindR estimate.
Do you believe that tailfindR misses these tails for some reason or is the squiggle actually misleading ?
 
Thank you for your time,
Arnaud

**Comment by ArnaudStigliani** [comment]
Note: I realized maybe too late that github may not be the place to ask these kind of questions. Please let me know if you prefer communicating by emails and do not hesitate to remove my issue.

**Comment by adnaniazi** [comment]
Hi Arnaud,

Yes, from the images you attached, it seems like tailfindr is prematuraly ending the longer tails. 

Since you have already a modified Dorado working for you, I recommend you just use that instead of tailfindr.  I can fix this bug for you in the jamie-Seq branch if I can get individual FAST5 files for these problematic reads. But I have left academia, and will no longer be in a position to keep on updating tailfindr or fix bugs constantly. So for your own project's sake, I recommend that you use Dorado instead as then you can be sure that you are using the latest tool that is constantly being developed and improved -- and not be dependent on an orphanware such as tailfindr.

Best,
Adnan

**Comment by ArnaudStigliani** [comment]
Hi Adnan,

Thanks a lot for your answer, I was not sure I was interpreting the results properly :) 
No need to correct the bug, (unless of course you really want to do it). As you say, it doesn't really make sense as Dorado keeps being updated. 

I wish you the best,
Arnaud
