### ISSUE TITLE
Fail to install package form GitHub

### ISSUE THREAD

**Issue by hannalee809** [adnaniazi/tailfinder#73]
Hi! I am having issues installing the tailfindr in RStudio (version 4.4.0). I've been able to install devtools and rbokeh successfully but when I try to install tailfindr using devtools, I get this error:

<img width="424" alt="Screenshot 2024-08-01 at 10 33 25 AM" src="https://github.com/user-attachments/assets/77e6ddb1-10c8-4db1-ad91-9a703c00a9ae">

Please let me know if you have any ideas to resolve this issue!

**Comment by adnaniazi** [comment]
Hi, 

To solve this error, you need to address the authentication issue. The error message indicates that there's a problem with the credentials being used to access the GitHub repository. Here are the steps to resolve this:

Check your GitHub credentials:

Ensure you have a valid GitHub Personal Access Token (PAT) set up.
Verify that the token has the necessary permissions to access the repository.


Configure your Git credentials:

Run`git config --global credential.helper store` to enable credential storage.
Then set your GitHub username and PAT:
```
git config --global user.name "Your GitHub Username"
git config --global user.password "Your GitHub PAT"
```

I would also recommend that you use Dorado instead of tailfindr for polyA tail profiling. I have left academia and will no longer update or develop it further. So for your project's sake, it is better that you use a tool that has a forseeable future.

Best,
Adnan

**Comment by hannalee809** [comment]
Hi, 

Thank you for your quick response. Sorry to see you go, but best of luck with everything!
